[phases.setup]
nixPkgs = ['deno', 'nodejs']
aptPkgs = ['curl']

[phases.build]
cmds = [
  'rm -f deno.lock',
  'deno cache --reload src/main.ts',
  'deno cache src/main.ts'
]

[start]
cmd = "deno run --allow-net --allow-read --allow-run --allow-env src/main.ts" 