[phases.setup]
nixPkgs = ['deno', 'nodejs']
aptPkgs = ['curl']

[phases.build]
cmds = [
  'deno cache --no-lock src/main.ts'
]

[start]
cmd = "deno run --no-lock --allow-net --allow-read --allow-run --allow-env src/main.ts" 